# Simulation comparison

This notebook runs three different simulators, Copula, TVAE, and per-protein, 
for the three experimental datasets included in this repository: CRC, MEL, and PDAC.

Note the PDAC experiments includes two acquisition (DIA+MRM) resulting in four 
simulations.

## Setup

In [1]:
import pandas as pd
from protmapper import uniprot_client
from indra.databases import hgnc_client

from MSquantSim.simulate import simulate_using_copula, simulate_using_tvae, \
    simulate_using_per_protein
from MSquantSim.downstreamanalysis import run_random_forest

import warnings
warnings.filterwarnings('ignore')

# CRC

## Load and prepare data

In [2]:
crc_input = pd.read_csv('../data/crc/data/crc_silvia_data.csv')
crc_input.head()

,A1AG2,AFM,AHSG,ANT3,AOC3,APOB,ATRN,BTD,C20orf3,CADM1,...,Q5JNX2,SERPINA1,SERPINA3,SERPINA6,SERPINA7,THBS1,TIMP1,VTN,VWF,Condition
0,14.238157,16.103019,19.951792,17.207936,10.032169,15.544774,14.383388,16.283071,10.667779,9.653029,...,19.028130,18.061091,14.218036,15.796849,13.581848,13.995686,11.578754,12.081352,10.661031,CRC
1,15.024111,16.020714,19.715919,17.297900,9.034144,15.131883,13.981723,16.249189,10.703279,9.624991,...,19.862536,17.610188,14.832327,15.815397,13.138445,13.707714,11.960974,12.838407,10.778432,CRC
2,15.631364,16.143800,19.710849,17.596254,10.381880,15.955302,14.635355,16.499158,11.183873,10.323191,...,19.501773,18.539972,15.308726,16.401770,13.742330,15.636962,12.155842,12.313155,11.185271,CRC
3,15.401365,16.276415,19.704377,17.422504,9.502960,15.714932,14.060700,16.277732,9.972982,9.994209,...,19.984664,17.401414,14.254241,16.310491,13.936894,15.517268,12.379265,10.679166,10.887855,CRC
4,16.003158,16.958207,20.420334,17.988199,9.648502,16.247330,14.203595,16.541422,12.581556,9.607492,...,20.467453,17.448008,16.231911,16.485833,14.167134,15.129106,12.169116,14.506106,11.254175,CRC

In [3]:
# Split into health and disease
crc_healthy = crc_input[crc_input['Condition'] == 'Healthy'].drop(columns=['Condition'])
crc_disease = crc_input[crc_input['Condition'] == 'CRC'].drop(columns=['Condition'])

## Copula

### Single simulation

In [ ]:
copula_sim_healthy = simulate_using_copula(
    crc_healthy, num_simulations=1, 
    samples_per_simulation=len(crc_healthy), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

copula_sim_disease = simulate_using_copula(
    crc_disease, num_simulations=1, 
    samples_per_simulation=len(crc_disease), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

### Multiple simulations

In [ ]:
copula_sim_healthy = simulate_using_copula(
    crc_healthy, num_simulations=10, 
    samples_per_simulation=len(crc_healthy), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

copula_sim_disease = simulate_using_copula(
    crc_disease, num_simulations=10, 
    samples_per_simulation=len(crc_disease), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=100
)

Running copula simulations:   0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:


  0%|          | 0/10 [00:00<?, ?it/s]

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:718: RuntimeWarning:

invalid value encountered in sqrt

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:723: RuntimeWarning:

The iteration is not making good progress, as measured by the
  improvement from the last ten iterations.

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide

/Users/kohler.d/opt/anaconda3/envs/MSquantSim/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:6338: RuntimeWarning:

divide by zero encountered in divide


## TVAE

### Single simulation

In [ ]:
tvae_sim_healthy = simulate_using_tvae(
    crc_healthy, None, num_simulations=1,
    samples_per_simulation=len(crc_healthy), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

tvae_sim_disease = simulate_using_tvae(
    crc_disease, None, num_simulations=1,
    samples_per_simulation=len(crc_disease), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

### Multiple simulations

In [ ]:
tvae_sim_healthy = simulate_using_tvae(
    crc_healthy, None, num_simulations=10,
    samples_per_simulation=len(crc_healthy), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

tvae_sim_disease = simulate_using_tvae(
    crc_disease, None, num_simulations=10,
    samples_per_simulation=len(crc_disease), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

Running tvae simulations:   0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

## Per-protein

### Single simulation

In [ ]:
pprotein_sim_healthy = simulate_using_per_protein(
    crc_healthy, num_simulations=1,
    samples_per_simulation=len(crc_healthy), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

pprotein_sim_disease = simulate_using_per_protein(
    crc_disease, num_simulations=1,
    samples_per_simulation=len(crc_disease), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

### Multiple simulations

In [ ]:
pprotein_sim_healthy = simulate_using_per_protein(
    crc_healthy, num_simulations=10,
    samples_per_simulation=len(crc_healthy), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

pprotein_sim_disease = simulate_using_per_protein(
    crc_disease, num_simulations=10,
    samples_per_simulation=len(crc_disease), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

Running per-protein simulations:   0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

# MEL

## Load and prepare data

In [35]:
mel_input = pd.read_csv('../data/mel/data/meldataclean.csv')
mel_input.head()

,DHX15_HUMAN,G3P_HUMAN,HSPB1_HUMAN,ENOA_HUMAN,NPM_HUMAN,HS90A_HUMAN,HNRPC_HUMAN,HS90B_HUMAN,ANXA5_HUMAN,H14_HUMAN,...,RS23_HUMAN,TYB10_HUMAN,RS4X_HUMAN,H4_HUMAN,RL23_HUMAN,HNRPU_HUMAN,PSME1_HUMAN,EF1A1_HUMAN,PARK7_HUMAN,BioReplicate
0,9.368920,10.167968,11.777913,10.920721,10.906010,10.335122,10.634692,11.553578,9.207920,11.360237,...,11.271160,13.482704,10.378637,10.531847,11.752979,10.405871,9.219097,9.846337,10.133048,0
1,9.489853,10.180817,10.818609,10.871440,10.889861,10.396813,10.330118,11.014594,9.597437,11.422972,...,11.973722,13.070122,10.517606,10.645003,11.238343,10.667812,9.916110,10.187284,10.553502,0
2,9.766231,10.706837,11.750412,12.442845,12.427367,11.026080,10.609098,11.076089,11.808549,11.638560,...,11.030231,12.587978,11.215166,11.626250,10.962162,11.166272,10.285818,10.185965,11.767151,1
3,10.048671,9.803506,11.674774,11.818872,11.919689,10.957868,10.552753,11.523332,11.582727,11.269536,...,11.456930,12.264780,9.961714,11.158386,10.938503,11.007130,9.975372,10.427651,10.365379,1
4,10.155918,10.459226,12.510192,11.998972,11.544736,11.230470,10.727446,11.372416,11.370214,11.708166,...,11.388214,11.661693,10.575094,11.426903,12.067473,11.155149,10.308901,9.994868,10.841175,1

In [37]:
def get_hgnc_from_uniprot_mnemonic(mnemonic):
    uniprot_id = uniprot_client.get_id_from_mnemonic(mnemonic)
    hgnc_id = uniprot_client.get_hgnc_id(uniprot_id)
    hgnc_name = hgnc_client.get_hgnc_name(hgnc_id)
    return hgnc_name

mel_input.columns = [get_hgnc_from_uniprot_mnemonic(i) if i != "BioReplicate" \
    else "BioReplicate" for i in mel_input.columns]

In [38]:
# Split into health and disease
mel_healthy = mel_input[mel_input['BioReplicate'] == 0].drop(columns=['BioReplicate'])
mel_disease = mel_input[mel_input['BioReplicate'] == 1].drop(columns=['BioReplicate'])

## Copula

### Single simulation

In [ ]:
copula_sim_mel_healthy_single = simulate_using_copula(
    mel_healthy, num_simulations=1, 
    samples_per_simulation=len(mel_healthy), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

copula_sim_mel_disease_single = simulate_using_copula(
    mel_disease, num_simulations=1, 
    samples_per_simulation=len(mel_disease), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

INFO: [2025-11-03 11:34:55] copulas.multivariate.gaussian - Fitting GaussianMultivariate()
INFO: [2025-11-03 11:35:04] copulas.multivariate.gaussian - Fitting GaussianMultivariate()

### Multiple simulations

In [ ]:
copula_sim_mel_healthy_multi = simulate_using_copula(
    mel_healthy, num_simulations=10, 
    samples_per_simulation=len(mel_healthy), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

copula_sim_mel_disease_multi = simulate_using_copula(
    mel_disease, num_simulations=10, 
    samples_per_simulation=len(mel_disease), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=100
)

Running copula simulations:   0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

## TVAE

### Single simulation

In [41]:
tvae_sim_mel_healthy_single = simulate_using_tvae(
    mel_healthy, None, num_simulations=1,
    samples_per_simulation=len(mel_healthy), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

tvae_sim_mel_disease_single = simulate_using_tvae(
    mel_disease, None, num_simulations=1,
    samples_per_simulation=len(mel_disease), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

INFO: [2025-11-03 11:37:54] sdv.metadata.single_table - Detected metadata:
INFO: [2025-11-03 11:37:54] sdv.metadata.single_table - {
    "columns": {
        "DHX15": {
            "sdtype": "numerical"
        },
        "GAPDH": {
            "sdtype": "numerical"
        },
        "HSPB1": {
            "sdtype": "numerical"
        },
        "ENO1": {
            "sdtype": "numerical"
        },
        "NPM1": {
            "sdtype": "numerical"
        },
        "HSP90AA1": {
            "sdtype": "numerical"
        },
        "HNRNPC": {
            "sdtype": "numerical"
        },
        "HSP90AB1": {
            "sdtype": "numerical"
        },
        "ANXA5": {
            "sdtype": "numerical"
        },
        "H1-4": {
            "sdtype": "numerical"
        },
        "HSPD1": {
            "sdtype": "numerical"
        },
        "PKM": {
            "sdtype": "numerical"
        },
        "HSP90B1": {
            "sdtype": "numerical"
        },
        "PGAM1": {
            "sdtype": "numerical"
        },
        "NCL": {
            "sdtype": "numerical"
        },
        "RPL13": {
            "sdtype": "numerical"
        },
        "CALR": {
            "sdtype": "numerical"
        },
        "S100A11": {
            "sdtype": "numerical"
        },
        "MYH10": {
            "sdtype": "numerical"
        },
        "RBMX": {
            "sdtype": "numerical"
        },
        "LRPPRC": {
            "sdtype": "numerical"
        },
        "RPL28": {
            "sdtype": "numerical"
        },
        "AARS1": {
            "sdtype": "numerical"
        },
        "HNRNPM": {
            "sdtype": "numerical"
        },
        "RPS23": {
            "sdtype": "numerical"
        },
        "TMSB10": {
            "sdtype": "numerical"
        },
        "RPS4X": {
            "sdtype": "numerical"
        },
        "H4C16": {
            "sdtype": "numerical"
        },
        "RPL23": {
            "sdtype": "numerical"
        },
        "HNRNPU": {
            "sdtype": "numerical"
        },
        "PSME1": {
            "sdtype": "numerical"
        },
        "EEF1A1": {
            "sdtype": "numerical"
        },
        "PARK7": {
            "sdtype": "numerical"
        }
    },
    "METADATA_SPEC_VERSION": "SINGLE_TABLE_V1"
}
Running copula simulations:   0%|          | 0/10 [01:44<?, ?it/s]
INFO: [2025-11-03 11:37:54] SingleTableSynthesizer - {'EVENT': 'Instance', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 11, 37, 54, 962385), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_d43f5e0df7934ac9ab83e829125ef739'}
INFO: [2025-11-03 11:37:54] SingleTableSynthesizer - {'EVENT': 'Fit', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 11, 37, 54, 964383), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_d43f5e0df7934ac9ab83e829125ef739', 'TOTAL NUMBER OF TABLES': 1, 'TOTAL NUMBER OF ROWS': 289, 'TOTAL NUMBER OF COLUMNS': 33}
INFO: [2025-11-03 11:37:54] sdv.data_processing.data_processor - Fitting table  metadata
INFO: [2025-11-03 11:37:54] sdv.data_processing.data_processor - Fitting formatters for table
INFO: [2025-11-03 11:37:55] sdv.data_processing.data_processor - Setting the configuration for the ``HyperTransformer`` for table
INFO: [2025-11-03 11:37:55] sdv.data_processing.data_processor - Fitting HyperTransformer for table
INFO: [2025-11-03 11:37:55] SingleTableSynthesizer - {'EVENT': 'Fit processed data', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 11, 37, 55, 187361), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_d43f5e0df7934ac9ab83e829125ef739', 'TOTAL NUMBER OF TABLES': 1, 'TOTAL NUMBER OF ROWS': 289, 'TOTAL NUMBER OF COLUMNS': 33}
INFO: [2025-11-03 11:37:55] rdt.transformers.null - Guidance: There are no missing values in column DHX15. Extra column not created.
INFO: [2025-11-03 11:37:55] rdt.transformers.null - Guidance: There are no missing values in column GAPDH. Extra column not created.
INFO: [2025-11-03 11:37:55] rdt.transformers.null - Guidance: There are no missing values in column HSPB1. Extra column not created.
INFO: [2025-11-03 11:37:55] rdt.transformers.null - Guidance: There are no missing values in column ENO1. Extra column not created.
INFO: [2025-11-03 11:37:55] rdt.transformers.null - Guidance: There are no missing values in column NPM1. Extra column not created.
INFO: [2025-11-03 11:37:55] rdt.transformers.null - Guidance: There are no missing values in column HSP90AA1. Extra column not created.
INFO: [2025-11-03 11:37:55] rdt.transformers.null - Guidance: There are no missing values in column HNRNPC. Extra column not created.
INFO: [2025-11-03 11:37:55] rdt.transformers.null - Guidance: There are no missing values in column HSP90AB1. Extra column not created.
INFO: [2025-11-03 11:37:55] rdt.transformers.null - Guidance: There are no missing values in column ANXA5. Extra column not created.
INFO: [2025-11-03 11:37:56] rdt.transformers.null - Guidance: There are no missing values in column H1-4. Extra column not created.
INFO: [2025-11-03 11:37:56] rdt.transformers.null - Guidance: There are no missing values in column HSPD1. Extra column not created.
INFO: [2025-11-03 11:37:56] rdt.transformers.null - Guidance: There are no missing values in column PKM. Extra column not created.
INFO: [2025-11-03 11:37:56] rdt.transformers.null - Guidance: There are no missing values in column HSP90B1. Extra column not created.
INFO: [2025-11-03 11:37:56] rdt.transformers.null - Guidance: There are no missing values in column PGAM1. Extra column not created.
INFO: [2025-11-03 11:37:56] rdt.transformers.null - Guidance: There are no missing values in column NCL. Extra column not created.
INFO: [2025-11-03 11:37:56] rdt.transformers.null - Guidance: There are no missing values in column RPL13. Extra column not created.
INFO: [2025-11-03 11:37:56] rdt.transformers.null - Guidance: There are no missing values in column CALR. Extra column not created.
INFO: [2025-11-03 11:37:56] rdt.transformers.null - Guidance: There are no missing values in column S100A11. Extra column not created.
INFO: [2025-11-03 11:37:56] rdt.transformers.null - Guidance: There are no missing values in column MYH10. Extra column not created.
INFO: [2025-11-03 11:37:56] rdt.transformers.null - Guidance: There are no missing values in column RBMX. Extra column not created.
INFO: [2025-11-03 11:37:56] rdt.transformers.null - Guidance: There are no missing values in column LRPPRC. Extra column not created.
INFO: [2025-11-03 11:37:56] rdt.transformers.null - Guidance: There are no missing values in column RPL28. Extra column not created.
INFO: [2025-11-03 11:37:57] rdt.transformers.null - Guidance: There are no missing values in column AARS1. Extra column not created.
INFO: [2025-11-03 11:37:57] rdt.transformers.null - Guidance: There are no missing values in column HNRNPM. Extra column not created.
INFO: [2025-11-03 11:37:57] rdt.transformers.null - Guidance: There are no missing values in column RPS23. Extra column not created.
INFO: [2025-11-03 11:37:57] rdt.transformers.null - Guidance: There are no missing values in column TMSB10. Extra column not created.
INFO: [2025-11-03 11:37:57] rdt.transformers.null - Guidance: There are no missing values in column RPS4X. Extra column not created.
INFO: [2025-11-03 11:37:57] rdt.transformers.null - Guidance: There are no missing values in column H4C16. Extra column not created.
INFO: [2025-11-03 11:37:57] rdt.transformers.null - Guidance: There are no missing values in column RPL23. Extra column not created.
INFO: [2025-11-03 11:37:57] rdt.transformers.null - Guidance: There are no missing values in column HNRNPU. Extra column not created.
INFO: [2025-11-03 11:37:57] rdt.transformers.null - Guidance: There are no missing values in column PSME1. Extra column not created.
INFO: [2025-11-03 11:37:57] rdt.transformers.null - Guidance: There are no missing values in column EEF1A1. Extra column not created.
INFO: [2025-11-03 11:37:57] rdt.transformers.null - Guidance: There are no missing values in column PARK7. Extra column not created.
INFO: [2025-11-03 11:38:12] SingleTableSynthesizer - {'EVENT': 'Sample', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 11, 38, 12, 140279), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_d43f5e0df7934ac9ab83e829125ef739', 'TOTAL NUMBER OF TABLES': 1, 'TOTAL NUMBER OF ROWS': 289, 'TOTAL NUMBER OF COLUMNS': 33}
INFO: [2025-11-03 11:38:12] sdv.metadata.single_table - Detected metadata:
INFO: [2025-11-03 11:38:12] sdv.metadata.single_table - {
    "columns": {
        "DHX15": {
            "sdtype": "numerical"
        },
        "GAPDH": {
            "sdtype": "numerical"
        },
        "HSPB1": {
            "sdtype": "numerical"
        },
        "ENO1": {
            "sdtype": "numerical"
        },
        "NPM1": {
            "sdtype": "numerical"
        },
        "HSP90AA1": {
            "sdtype": "numerical"
        },
        "HNRNPC": {
            "sdtype": "numerical"
        },
        "HSP90AB1": {
            "sdtype": "numerical"
        },
        "ANXA5": {
            "sdtype": "numerical"
        },
        "H1-4": {
            "sdtype": "numerical"
        },
        "HSPD1": {
            "sdtype": "numerical"
        },
        "PKM": {
            "sdtype": "numerical"
        },
        "HSP90B1": {
            "sdtype": "numerical"
        },
        "PGAM1": {
            "sdtype": "numerical"
        },
        "NCL": {
            "sdtype": "numerical"
        },
        "RPL13": {
            "sdtype": "numerical"
        },
        "CALR": {
            "sdtype": "numerical"
        },
        "S100A11": {
            "sdtype": "numerical"
        },
        "MYH10": {
            "sdtype": "numerical"
        },
        "RBMX": {
            "sdtype": "numerical"
        },
        "LRPPRC": {
            "sdtype": "numerical"
        },
        "RPL28": {
            "sdtype": "numerical"
        },
        "AARS1": {
            "sdtype": "numerical"
        },
        "HNRNPM": {
            "sdtype": "numerical"
        },
        "RPS23": {
            "sdtype": "numerical"
        },
        "TMSB10": {
            "sdtype": "numerical"
        },
        "RPS4X": {
            "sdtype": "numerical"
        },
        "H4C16": {
            "sdtype": "numerical"
        },
        "RPL23": {
            "sdtype": "numerical"
        },
        "HNRNPU": {
            "sdtype": "numerical"
        },
        "PSME1": {
            "sdtype": "numerical"
        },
        "EEF1A1": {
            "sdtype": "numerical"
        },
        "PARK7": {
            "sdtype": "numerical"
        }
    },
    "METADATA_SPEC_VERSION": "SINGLE_TABLE_V1"
}
INFO: [2025-11-03 11:38:12] SingleTableSynthesizer - {'EVENT': 'Instance', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 11, 38, 12, 297258), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_969ebdf59d5b488fb2e64e2e1782561d'}
INFO: [2025-11-03 11:38:12] SingleTableSynthesizer - {'EVENT': 'Fit', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 11, 38, 12, 297701), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_969ebdf59d5b488fb2e64e2e1782561d', 'TOTAL NUMBER OF TABLES': 1, 'TOTAL NUMBER OF ROWS': 289, 'TOTAL NUMBER OF COLUMNS': 33}
INFO: [2025-11-03 11:38:12] sdv.data_processing.data_processor - Fitting table  metadata
INFO: [2025-11-03 11:38:12] sdv.data_processing.data_processor - Fitting formatters for table
INFO: [2025-11-03 11:38:12] sdv.data_processing.data_processor - Setting the configuration for the ``HyperTransformer`` for table
INFO: [2025-11-03 11:38:12] sdv.data_processing.data_processor - Fitting HyperTransformer for table
INFO: [2025-11-03 11:38:12] SingleTableSynthesizer - {'EVENT': 'Fit processed data', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 11, 38, 12, 507379), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_969ebdf59d5b488fb2e64e2e1782561d', 'TOTAL NUMBER OF TABLES': 1, 'TOTAL NUMBER OF ROWS': 289, 'TOTAL NUMBER OF COLUMNS': 33}
INFO: [2025-11-03 11:38:12] rdt.transformers.null - Guidance: There are no missing values in column DHX15. Extra column not created.
INFO: [2025-11-03 11:38:12] rdt.transformers.null - Guidance: There are no missing values in column GAPDH. Extra column not created.
INFO: [2025-11-03 11:38:12] rdt.transformers.null - Guidance: There are no missing values in column HSPB1. Extra column not created.
INFO: [2025-11-03 11:38:12] rdt.transformers.null - Guidance: There are no missing values in column ENO1. Extra column not created.
INFO: [2025-11-03 11:38:12] rdt.transformers.null - Guidance: There are no missing values in column NPM1. Extra column not created.
INFO: [2025-11-03 11:38:12] rdt.transformers.null - Guidance: There are no missing values in column HSP90AA1. Extra column not created.
INFO: [2025-11-03 11:38:12] rdt.transformers.null - Guidance: There are no missing values in column HNRNPC. Extra column not created.
INFO: [2025-11-03 11:38:13] rdt.transformers.null - Guidance: There are no missing values in column HSP90AB1. Extra column not created.
INFO: [2025-11-03 11:38:13] rdt.transformers.null - Guidance: There are no missing values in column ANXA5. Extra column not created.
INFO: [2025-11-03 11:38:13] rdt.transformers.null - Guidance: There are no missing values in column H1-4. Extra column not created.
INFO: [2025-11-03 11:38:13] rdt.transformers.null - Guidance: There are no missing values in column HSPD1. Extra column not created.
INFO: [2025-11-03 11:38:13] rdt.transformers.null - Guidance: There are no missing values in column PKM. Extra column not created.
INFO: [2025-11-03 11:38:13] rdt.transformers.null - Guidance: There are no missing values in column HSP90B1. Extra column not created.
INFO: [2025-11-03 11:38:13] rdt.transformers.null - Guidance: There are no missing values in column PGAM1. Extra column not created.
INFO: [2025-11-03 11:38:13] rdt.transformers.null - Guidance: There are no missing values in column NCL. Extra column not created.
INFO: [2025-11-03 11:38:13] rdt.transformers.null - Guidance: There are no missing values in column RPL13. Extra column not created.
INFO: [2025-11-03 11:38:13] rdt.transformers.null - Guidance: There are no missing values in column CALR. Extra column not created.
INFO: [2025-11-03 11:38:13] rdt.transformers.null - Guidance: There are no missing values in column S100A11. Extra column not created.
INFO: [2025-11-03 11:38:13] rdt.transformers.null - Guidance: There are no missing values in column MYH10. Extra column not created.
INFO: [2025-11-03 11:38:14] rdt.transformers.null - Guidance: There are no missing values in column RBMX. Extra column not created.
INFO: [2025-11-03 11:38:14] rdt.transformers.null - Guidance: There are no missing values in column LRPPRC. Extra column not created.
INFO: [2025-11-03 11:38:14] rdt.transformers.null - Guidance: There are no missing values in column RPL28. Extra column not created.
INFO: [2025-11-03 11:38:14] rdt.transformers.null - Guidance: There are no missing values in column AARS1. Extra column not created.
INFO: [2025-11-03 11:38:14] rdt.transformers.null - Guidance: There are no missing values in column HNRNPM. Extra column not created.
INFO: [2025-11-03 11:38:14] rdt.transformers.null - Guidance: There are no missing values in column RPS23. Extra column not created.
INFO: [2025-11-03 11:38:14] rdt.transformers.null - Guidance: There are no missing values in column TMSB10. Extra column not created.
INFO: [2025-11-03 11:38:14] rdt.transformers.null - Guidance: There are no missing values in column RPS4X. Extra column not created.
INFO: [2025-11-03 11:38:14] rdt.transformers.null - Guidance: There are no missing values in column H4C16. Extra column not created.
INFO: [2025-11-03 11:38:14] rdt.transformers.null - Guidance: There are no missing values in column RPL23. Extra column not created.
INFO: [2025-11-03 11:38:14] rdt.transformers.null - Guidance: There are no missing values in column HNRNPU. Extra column not created.
INFO: [2025-11-03 11:38:14] rdt.transformers.null - Guidance: There are no missing values in column PSME1. Extra column not created.
INFO: [2025-11-03 11:38:15] rdt.transformers.null - Guidance: There are no missing values in column EEF1A1. Extra column not created.
INFO: [2025-11-03 11:38:15] rdt.transformers.null - Guidance: There are no missing values in column PARK7. Extra column not created.
INFO: [2025-11-03 11:38:25] SingleTableSynthesizer - {'EVENT': 'Sample', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 11, 38, 25, 798304), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_969ebdf59d5b488fb2e64e2e1782561d', 'TOTAL NUMBER OF TABLES': 1, 'TOTAL NUMBER OF ROWS': 289, 'TOTAL NUMBER OF COLUMNS': 33}

### Multiple simulations

In [43]:
tvae_sim_mel_healthy_multi = simulate_using_tvae(
    mel_healthy, None, num_simulations=10,
    samples_per_simulation=len(mel_healthy), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

tvae_sim_mel_disease_multi = simulate_using_tvae(
    mel_disease, None, num_simulations=10,
    samples_per_simulation=len(mel_disease), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

INFO: [2025-11-03 11:47:20] sdv.metadata.single_table - Detected metadata:
INFO: [2025-11-03 11:47:20] sdv.metadata.single_table - {
    "columns": {
        "DHX15": {
            "sdtype": "numerical"
        },
        "GAPDH": {
            "sdtype": "numerical"
        },
        "HSPB1": {
            "sdtype": "numerical"
        },
        "ENO1": {
            "sdtype": "numerical"
        },
        "NPM1": {
            "sdtype": "numerical"
        },
        "HSP90AA1": {
            "sdtype": "numerical"
        },
        "HNRNPC": {
            "sdtype": "numerical"
        },
        "HSP90AB1": {
            "sdtype": "numerical"
        },
        "ANXA5": {
            "sdtype": "numerical"
        },
        "H1-4": {
            "sdtype": "numerical"
        },
        "HSPD1": {
            "sdtype": "numerical"
        },
        "PKM": {
            "sdtype": "numerical"
        },
        "HSP90B1": {
            "sdtype": "numerical"
        },
        "PGAM1": {
            "sdtype": "numerical"
        },
        "NCL": {
            "sdtype": "numerical"
        },
        "RPL13": {
            "sdtype": "numerical"
        },
        "CALR": {
            "sdtype": "numerical"
        },
        "S100A11": {
            "sdtype": "numerical"
        },
        "MYH10": {
            "sdtype": "numerical"
        },
        "RBMX": {
            "sdtype": "numerical"
        },
        "LRPPRC": {
            "sdtype": "numerical"
        },
        "RPL28": {
            "sdtype": "numerical"
        },
        "AARS1": {
            "sdtype": "numerical"
        },
        "HNRNPM": {
            "sdtype": "numerical"
        },
        "RPS23": {
            "sdtype": "numerical"
        },
        "TMSB10": {
            "sdtype": "numerical"
        },
        "RPS4X": {
            "sdtype": "numerical"
        },
        "H4C16": {
            "sdtype": "numerical"
        },
        "RPL23": {
            "sdtype": "numerical"
        },
        "HNRNPU": {
            "sdtype": "numerical"
        },
        "PSME1": {
            "sdtype": "numerical"
        },
        "EEF1A1": {
            "sdtype": "numerical"
        },
        "PARK7": {
            "sdtype": "numerical"
        }
    },
    "METADATA_SPEC_VERSION": "SINGLE_TABLE_V1"
}
Running tvae simulations:   0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

INFO: [2025-11-03 11:48:13] sdv.metadata.single_table - Detected metadata:
INFO: [2025-11-03 11:48:13] sdv.metadata.single_table - {
    "columns": {
        "DHX15": {
            "sdtype": "numerical"
        },
        "GAPDH": {
            "sdtype": "numerical"
        },
        "HSPB1": {
            "sdtype": "numerical"
        },
        "ENO1": {
            "sdtype": "numerical"
        },
        "NPM1": {
            "sdtype": "numerical"
        },
        "HSP90AA1": {
            "sdtype": "numerical"
        },
        "HNRNPC": {
            "sdtype": "numerical"
        },
        "HSP90AB1": {
            "sdtype": "numerical"
        },
        "ANXA5": {
            "sdtype": "numerical"
        },
        "H1-4": {
            "sdtype": "numerical"
        },
        "HSPD1": {
            "sdtype": "numerical"
        },
        "PKM": {
            "sdtype": "numerical"
        },
        "HSP90B1": {
            "sdtype": "numerical"
        },
        "PGAM1": {
            "sdtype": "numerical"
        },
        "NCL": {
            "sdtype": "numerical"
        },
        "RPL13": {
            "sdtype": "numerical"
        },
        "CALR": {
            "sdtype": "numerical"
        },
        "S100A11": {
            "sdtype": "numerical"
        },
        "MYH10": {
            "sdtype": "numerical"
        },
        "RBMX": {
            "sdtype": "numerical"
        },
        "LRPPRC": {
            "sdtype": "numerical"
        },
        "RPL28": {
            "sdtype": "numerical"
        },
        "AARS1": {
            "sdtype": "numerical"
        },
        "HNRNPM": {
            "sdtype": "numerical"
        },
        "RPS23": {
            "sdtype": "numerical"
        },
        "TMSB10": {
            "sdtype": "numerical"
        },
        "RPS4X": {
            "sdtype": "numerical"
        },
        "H4C16": {
            "sdtype": "numerical"
        },
        "RPL23": {
            "sdtype": "numerical"
        },
        "HNRNPU": {
            "sdtype": "numerical"
        },
        "PSME1": {
            "sdtype": "numerical"
        },
        "EEF1A1": {
            "sdtype": "numerical"
        },
        "PARK7": {
            "sdtype": "numerical"
        }
    },
    "METADATA_SPEC_VERSION": "SINGLE_TABLE_V1"
}

  0%|          | 0/10 [00:00<?, ?it/s]

## Per-protein

### Single simulation

In [ ]:
pprotein_sim_mel_healthy_single = simulate_using_per_protein(
    mel_healthy, num_simulations=1,
    samples_per_simulation=len(mel_healthy), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

pprotein_sim_mel_disease_single = simulate_using_per_protein(
    mel_disease, num_simulations=1,
    samples_per_simulation=len(mel_disease), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

### Multiple simulations

In [ ]:
pprotein_sim_mel_healthy_multi = simulate_using_per_protein(
    mel_healthy, num_simulations=10,
    samples_per_simulation=len(mel_healthy), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

pprotein_sim_mel_disease_multi = simulate_using_per_protein(
    mel_disease, num_simulations=10,
    samples_per_simulation=len(mel_disease), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

Running per-protein simulations:   0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

# PDAC - DIA

## Load and prepare data

In [44]:
pdac_dia_input = pd.read_csv('../data/pdac/pdacdia/data/pdac15diadata.csv')
pdac_dia_input.head()

,ANPEP,APOA4,APOC3,C9,CRP,HGFAC,IGFBP2,ITIH3,LRG1,ORM1,PFN1,PIGR,PON3,SERPINA3,VWF,Sample type
0,0.0098,1.7243,7.1236,0.4633,0.0116,0.0936,0.0160,0.1889,0.4178,6.5454,0.0739,0.0239,0.0141,5.0207,0.0508,Healthy
1,0.0119,2.7745,5.1915,0.2742,0.0288,0.1260,0.0162,0.2278,0.3690,4.0885,0.0887,0.0216,0.0087,5.2092,0.0329,Healthy
2,0.0130,1.3658,5.4925,0.1902,0.0650,0.0937,0.0130,0.2176,0.4777,6.6011,0.1285,0.0661,0.0050,4.1751,0.0288,Healthy
3,0.0087,1.8386,4.2463,0.1907,0.0115,0.1283,0.0291,0.2169,0.2952,3.1604,0.0728,0.0285,0.0056,3.7827,0.0430,Healthy
4,0.0271,1.3240,2.9771,0.7515,0.2795,0.1292,0.0507,0.4905,1.0433,8.8970,0.1134,0.0895,0.0083,6.9957,0.1076,Healthy

In [50]:
# Split into health and disease
pdac_dia_input_healthy = pdac_dia_input[pdac_dia_input['Sample type'] == "Healthy"].drop(columns=['Sample type'])
pdac_dia_input_disease = pdac_dia_input[pdac_dia_input['Sample type'] == "PDAC"].drop(columns=['Sample type'])
pdac_dia_input_benign = pdac_dia_input[pdac_dia_input['Sample type'] == "Benign"].drop(columns=['Sample type'])

## Copula

### Single simulation

In [53]:
copula_sim_pdac_healthy_single = simulate_using_copula(
    pdac_dia_input_healthy, num_simulations=1, 
    samples_per_simulation=len(pdac_dia_input_healthy), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

copula_sim_pdac_disease_single = simulate_using_copula(
    pdac_dia_input_disease, num_simulations=1, 
    samples_per_simulation=len(pdac_dia_input_disease), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

copula_sim_pdac_benign_single = simulate_using_copula(
    pdac_dia_input_benign, num_simulations=1, 
    samples_per_simulation=len(pdac_dia_input_benign), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

INFO: [2025-11-03 11:55:55] copulas.multivariate.gaussian - Fitting GaussianMultivariate()
INFO: [2025-11-03 11:55:58] copulas.multivariate.gaussian - Fitting GaussianMultivariate()
INFO: [2025-11-03 11:56:01] copulas.multivariate.gaussian - Fitting GaussianMultivariate()

### Multiple simulations

In [54]:
copula_sim_pdac_healthy_multi = simulate_using_copula(
    pdac_dia_input_healthy, num_simulations=10, 
    samples_per_simulation=len(pdac_dia_input_healthy), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

copula_sim_pdac_disease_multi = simulate_using_copula(
    pdac_dia_input_disease, num_simulations=10, 
    samples_per_simulation=len(pdac_dia_input_disease), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=100
)

copula_sim_pdac_benign_multi = simulate_using_copula(
    pdac_dia_input_benign, num_simulations=10, 
    samples_per_simulation=len(pdac_dia_input_benign), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=100
)

Running copula simulations:   0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

Running copula simulations:   0%|          | 0/10 [00:00<?, ?it/s]IOStream.flush timed out
IOStream.flush timed out
IOStream.flush timed out
Running copula simulations:   0%|          | 0/10 [00:38<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

## TVAE

### Single simulation

In [55]:
tvae_sim_pdac_healthy_single = simulate_using_tvae(
    pdac_dia_input_healthy, None, num_simulations=1,
    samples_per_simulation=len(pdac_dia_input_healthy), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

tvae_sim_pdac_disease_single = simulate_using_tvae(
    pdac_dia_input_disease, None, num_simulations=1,
    samples_per_simulation=len(pdac_dia_input_disease),
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

tvae_sim_pdac_benign_single = simulate_using_tvae(
    pdac_dia_input_benign, None, num_simulations=1,
    samples_per_simulation=len(pdac_dia_input_benign), 
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

INFO: [2025-11-03 11:59:04] sdv.metadata.single_table - Detected metadata:
INFO: [2025-11-03 11:59:04] sdv.metadata.single_table - {
    "columns": {
        "ANPEP": {
            "sdtype": "numerical"
        },
        "APOA4": {
            "sdtype": "numerical"
        },
        "APOC3": {
            "sdtype": "numerical"
        },
        "C9": {
            "sdtype": "numerical"
        },
        "CRP": {
            "sdtype": "numerical"
        },
        "HGFAC": {
            "sdtype": "numerical"
        },
        "IGFBP2": {
            "sdtype": "numerical"
        },
        "ITIH3": {
            "sdtype": "numerical"
        },
        "LRG1": {
            "sdtype": "numerical"
        },
        "ORM1": {
            "sdtype": "numerical"
        },
        "PFN1": {
            "sdtype": "numerical"
        },
        "PIGR": {
            "sdtype": "numerical"
        },
        "PON3": {
            "sdtype": "numerical"
        },
        "SERPINA3": {
            "sdtype": "numerical"
        },
        "VWF": {
            "sdtype": "numerical"
        }
    },
    "METADATA_SPEC_VERSION": "SINGLE_TABLE_V1"
}
Running copula simulations:   0%|          | 0/10 [02:47<?, ?it/s]
Running copula simulations:   0%|          | 0/10 [01:41<?, ?it/s]
INFO: [2025-11-03 11:59:04] SingleTableSynthesizer - {'EVENT': 'Instance', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 11, 59, 4, 421788), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_2f6117efed724c9bac6aa510aea5fbb5'}
INFO: [2025-11-03 11:59:04] SingleTableSynthesizer - {'EVENT': 'Fit', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 11, 59, 4, 422813), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_2f6117efed724c9bac6aa510aea5fbb5', 'TOTAL NUMBER OF TABLES': 1, 'TOTAL NUMBER OF ROWS': 152, 'TOTAL NUMBER OF COLUMNS': 15}
INFO: [2025-11-03 11:59:04] sdv.data_processing.data_processor - Fitting table  metadata
INFO: [2025-11-03 11:59:04] sdv.data_processing.data_processor - Fitting formatters for table
INFO: [2025-11-03 11:59:04] sdv.data_processing.data_processor - Setting the configuration for the ``HyperTransformer`` for table
INFO: [2025-11-03 11:59:04] sdv.data_processing.data_processor - Fitting HyperTransformer for table
INFO: [2025-11-03 11:59:04] SingleTableSynthesizer - {'EVENT': 'Fit processed data', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 11, 59, 4, 522775), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_2f6117efed724c9bac6aa510aea5fbb5', 'TOTAL NUMBER OF TABLES': 1, 'TOTAL NUMBER OF ROWS': 152, 'TOTAL NUMBER OF COLUMNS': 15}
INFO: [2025-11-03 11:59:04] rdt.transformers.null - Guidance: There are no missing values in column ANPEP. Extra column not created.
INFO: [2025-11-03 11:59:04] rdt.transformers.null - Guidance: There are no missing values in column APOA4. Extra column not created.
INFO: [2025-11-03 11:59:04] rdt.transformers.null - Guidance: There are no missing values in column APOC3. Extra column not created.
INFO: [2025-11-03 11:59:04] rdt.transformers.null - Guidance: There are no missing values in column C9. Extra column not created.
INFO: [2025-11-03 11:59:04] rdt.transformers.null - Guidance: There are no missing values in column CRP. Extra column not created.
INFO: [2025-11-03 11:59:04] rdt.transformers.null - Guidance: There are no missing values in column HGFAC. Extra column not created.
INFO: [2025-11-03 11:59:04] rdt.transformers.null - Guidance: There are no missing values in column IGFBP2. Extra column not created.
INFO: [2025-11-03 11:59:04] rdt.transformers.null - Guidance: There are no missing values in column ITIH3. Extra column not created.
INFO: [2025-11-03 11:59:04] rdt.transformers.null - Guidance: There are no missing values in column LRG1. Extra column not created.
INFO: [2025-11-03 11:59:05] rdt.transformers.null - Guidance: There are no missing values in column ORM1. Extra column not created.
INFO: [2025-11-03 11:59:05] rdt.transformers.null - Guidance: There are no missing values in column PFN1. Extra column not created.
INFO: [2025-11-03 11:59:05] rdt.transformers.null - Guidance: There are no missing values in column PIGR. Extra column not created.
INFO: [2025-11-03 11:59:05] rdt.transformers.null - Guidance: There are no missing values in column PON3. Extra column not created.
INFO: [2025-11-03 11:59:05] rdt.transformers.null - Guidance: There are no missing values in column SERPINA3. Extra column not created.
INFO: [2025-11-03 11:59:05] rdt.transformers.null - Guidance: There are no missing values in column VWF. Extra column not created.
INFO: [2025-11-03 11:59:11] SingleTableSynthesizer - {'EVENT': 'Sample', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 11, 59, 11, 115945), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_2f6117efed724c9bac6aa510aea5fbb5', 'TOTAL NUMBER OF TABLES': 1, 'TOTAL NUMBER OF ROWS': 152, 'TOTAL NUMBER OF COLUMNS': 15}
INFO: [2025-11-03 11:59:11] sdv.metadata.single_table - Detected metadata:
INFO: [2025-11-03 11:59:11] sdv.metadata.single_table - {
    "columns": {
        "ANPEP": {
            "sdtype": "numerical"
        },
        "APOA4": {
            "sdtype": "numerical"
        },
        "APOC3": {
            "sdtype": "numerical"
        },
        "C9": {
            "sdtype": "numerical"
        },
        "CRP": {
            "sdtype": "numerical"
        },
        "HGFAC": {
            "sdtype": "numerical"
        },
        "IGFBP2": {
            "sdtype": "numerical"
        },
        "ITIH3": {
            "sdtype": "numerical"
        },
        "LRG1": {
            "sdtype": "numerical"
        },
        "ORM1": {
            "sdtype": "numerical"
        },
        "PFN1": {
            "sdtype": "numerical"
        },
        "PIGR": {
            "sdtype": "numerical"
        },
        "PON3": {
            "sdtype": "numerical"
        },
        "SERPINA3": {
            "sdtype": "numerical"
        },
        "VWF": {
            "sdtype": "numerical"
        }
    },
    "METADATA_SPEC_VERSION": "SINGLE_TABLE_V1"
}
INFO: [2025-11-03 11:59:11] SingleTableSynthesizer - {'EVENT': 'Instance', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 11, 59, 11, 220743), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_cc4739a72db845cbbbedce2a518a2057'}
INFO: [2025-11-03 11:59:11] SingleTableSynthesizer - {'EVENT': 'Fit', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 11, 59, 11, 221202), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_cc4739a72db845cbbbedce2a518a2057', 'TOTAL NUMBER OF TABLES': 1, 'TOTAL NUMBER OF ROWS': 154, 'TOTAL NUMBER OF COLUMNS': 15}
INFO: [2025-11-03 11:59:11] sdv.data_processing.data_processor - Fitting table  metadata
INFO: [2025-11-03 11:59:11] sdv.data_processing.data_processor - Fitting formatters for table
INFO: [2025-11-03 11:59:11] sdv.data_processing.data_processor - Setting the configuration for the ``HyperTransformer`` for table
INFO: [2025-11-03 11:59:11] sdv.data_processing.data_processor - Fitting HyperTransformer for table
INFO: [2025-11-03 11:59:11] SingleTableSynthesizer - {'EVENT': 'Fit processed data', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 11, 59, 11, 306841), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_cc4739a72db845cbbbedce2a518a2057', 'TOTAL NUMBER OF TABLES': 1, 'TOTAL NUMBER OF ROWS': 154, 'TOTAL NUMBER OF COLUMNS': 15}
INFO: [2025-11-03 11:59:11] rdt.transformers.null - Guidance: There are no missing values in column ANPEP. Extra column not created.
INFO: [2025-11-03 11:59:11] rdt.transformers.null - Guidance: There are no missing values in column APOA4. Extra column not created.
INFO: [2025-11-03 11:59:11] rdt.transformers.null - Guidance: There are no missing values in column APOC3. Extra column not created.
INFO: [2025-11-03 11:59:11] rdt.transformers.null - Guidance: There are no missing values in column C9. Extra column not created.
INFO: [2025-11-03 11:59:11] rdt.transformers.null - Guidance: There are no missing values in column CRP. Extra column not created.
INFO: [2025-11-03 11:59:11] rdt.transformers.null - Guidance: There are no missing values in column HGFAC. Extra column not created.
INFO: [2025-11-03 11:59:11] rdt.transformers.null - Guidance: There are no missing values in column IGFBP2. Extra column not created.
INFO: [2025-11-03 11:59:11] rdt.transformers.null - Guidance: There are no missing values in column ITIH3. Extra column not created.
INFO: [2025-11-03 11:59:11] rdt.transformers.null - Guidance: There are no missing values in column LRG1. Extra column not created.
INFO: [2025-11-03 11:59:11] rdt.transformers.null - Guidance: There are no missing values in column ORM1. Extra column not created.
INFO: [2025-11-03 11:59:11] rdt.transformers.null - Guidance: There are no missing values in column PFN1. Extra column not created.
INFO: [2025-11-03 11:59:11] rdt.transformers.null - Guidance: There are no missing values in column PIGR. Extra column not created.
INFO: [2025-11-03 11:59:11] rdt.transformers.null - Guidance: There are no missing values in column PON3. Extra column not created.
INFO: [2025-11-03 11:59:11] rdt.transformers.null - Guidance: There are no missing values in column SERPINA3. Extra column not created.
INFO: [2025-11-03 11:59:12] rdt.transformers.null - Guidance: There are no missing values in column VWF. Extra column not created.
INFO: [2025-11-03 11:59:17] SingleTableSynthesizer - {'EVENT': 'Sample', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 11, 59, 17, 459239), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_cc4739a72db845cbbbedce2a518a2057', 'TOTAL NUMBER OF TABLES': 1, 'TOTAL NUMBER OF ROWS': 154, 'TOTAL NUMBER OF COLUMNS': 15}
INFO: [2025-11-03 11:59:17] sdv.metadata.single_table - Detected metadata:
INFO: [2025-11-03 11:59:17] sdv.metadata.single_table - {
    "columns": {
        "ANPEP": {
            "sdtype": "numerical"
        },
        "APOA4": {
            "sdtype": "numerical"
        },
        "APOC3": {
            "sdtype": "numerical"
        },
        "C9": {
            "sdtype": "numerical"
        },
        "CRP": {
            "sdtype": "numerical"
        },
        "HGFAC": {
            "sdtype": "numerical"
        },
        "IGFBP2": {
            "sdtype": "numerical"
        },
        "ITIH3": {
            "sdtype": "numerical"
        },
        "LRG1": {
            "sdtype": "numerical"
        },
        "ORM1": {
            "sdtype": "numerical"
        },
        "PFN1": {
            "sdtype": "numerical"
        },
        "PIGR": {
            "sdtype": "numerical"
        },
        "PON3": {
            "sdtype": "numerical"
        },
        "SERPINA3": {
            "sdtype": "numerical"
        },
        "VWF": {
            "sdtype": "numerical"
        }
    },
    "METADATA_SPEC_VERSION": "SINGLE_TABLE_V1"
}
INFO: [2025-11-03 11:59:17] SingleTableSynthesizer - {'EVENT': 'Instance', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 11, 59, 17, 533121), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_757ab27d11ef46998370fb9630d774ca'}
INFO: [2025-11-03 11:59:17] SingleTableSynthesizer - {'EVENT': 'Fit', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 11, 59, 17, 533553), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_757ab27d11ef46998370fb9630d774ca', 'TOTAL NUMBER OF TABLES': 1, 'TOTAL NUMBER OF ROWS': 50, 'TOTAL NUMBER OF COLUMNS': 15}
INFO: [2025-11-03 11:59:17] sdv.data_processing.data_processor - Fitting table  metadata
INFO: [2025-11-03 11:59:17] sdv.data_processing.data_processor - Fitting formatters for table
INFO: [2025-11-03 11:59:17] sdv.data_processing.data_processor - Setting the configuration for the ``HyperTransformer`` for table
INFO: [2025-11-03 11:59:17] sdv.data_processing.data_processor - Fitting HyperTransformer for table
INFO: [2025-11-03 11:59:17] SingleTableSynthesizer - {'EVENT': 'Fit processed data', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 11, 59, 17, 626766), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_757ab27d11ef46998370fb9630d774ca', 'TOTAL NUMBER OF TABLES': 1, 'TOTAL NUMBER OF ROWS': 50, 'TOTAL NUMBER OF COLUMNS': 15}
INFO: [2025-11-03 11:59:17] rdt.transformers.null - Guidance: There are no missing values in column ANPEP. Extra column not created.
INFO: [2025-11-03 11:59:17] rdt.transformers.null - Guidance: There are no missing values in column APOA4. Extra column not created.
INFO: [2025-11-03 11:59:17] rdt.transformers.null - Guidance: There are no missing values in column APOC3. Extra column not created.
INFO: [2025-11-03 11:59:17] rdt.transformers.null - Guidance: There are no missing values in column C9. Extra column not created.
INFO: [2025-11-03 11:59:17] rdt.transformers.null - Guidance: There are no missing values in column CRP. Extra column not created.
INFO: [2025-11-03 11:59:17] rdt.transformers.null - Guidance: There are no missing values in column HGFAC. Extra column not created.
INFO: [2025-11-03 11:59:17] rdt.transformers.null - Guidance: There are no missing values in column IGFBP2. Extra column not created.
INFO: [2025-11-03 11:59:17] rdt.transformers.null - Guidance: There are no missing values in column ITIH3. Extra column not created.
INFO: [2025-11-03 11:59:17] rdt.transformers.null - Guidance: There are no missing values in column LRG1. Extra column not created.
INFO: [2025-11-03 11:59:18] rdt.transformers.null - Guidance: There are no missing values in column ORM1. Extra column not created.
INFO: [2025-11-03 11:59:18] rdt.transformers.null - Guidance: There are no missing values in column PFN1. Extra column not created.
INFO: [2025-11-03 11:59:18] rdt.transformers.null - Guidance: There are no missing values in column PIGR. Extra column not created.
INFO: [2025-11-03 11:59:18] rdt.transformers.null - Guidance: There are no missing values in column PON3. Extra column not created.
INFO: [2025-11-03 11:59:18] rdt.transformers.null - Guidance: There are no missing values in column SERPINA3. Extra column not created.
INFO: [2025-11-03 11:59:18] rdt.transformers.null - Guidance: There are no missing values in column VWF. Extra column not created.
INFO: [2025-11-03 11:59:23] SingleTableSynthesizer - {'EVENT': 'Sample', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 11, 59, 23, 378830), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_757ab27d11ef46998370fb9630d774ca', 'TOTAL NUMBER OF TABLES': 1, 'TOTAL NUMBER OF ROWS': 50, 'TOTAL NUMBER OF COLUMNS': 15}

### Multiple simulations

In [56]:
tvae_sim_pdac_healthy_multi = simulate_using_tvae(
    pdac_dia_input_healthy, None, num_simulations=10,
    samples_per_simulation=len(pdac_dia_input_healthy), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

tvae_sim_pdac_disease_multi = simulate_using_tvae(
    pdac_dia_input_disease, None, num_simulations=10,
    samples_per_simulation=len(pdac_dia_input_disease), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

tvae_sim_pdac_benign_multi = simulate_using_tvae(
    pdac_dia_input_benign, None, num_simulations=10,
    samples_per_simulation=len(pdac_dia_input_benign), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

INFO: [2025-11-03 11:59:23] sdv.metadata.single_table - Detected metadata:
INFO: [2025-11-03 11:59:23] sdv.metadata.single_table - {
    "columns": {
        "ANPEP": {
            "sdtype": "numerical"
        },
        "APOA4": {
            "sdtype": "numerical"
        },
        "APOC3": {
            "sdtype": "numerical"
        },
        "C9": {
            "sdtype": "numerical"
        },
        "CRP": {
            "sdtype": "numerical"
        },
        "HGFAC": {
            "sdtype": "numerical"
        },
        "IGFBP2": {
            "sdtype": "numerical"
        },
        "ITIH3": {
            "sdtype": "numerical"
        },
        "LRG1": {
            "sdtype": "numerical"
        },
        "ORM1": {
            "sdtype": "numerical"
        },
        "PFN1": {
            "sdtype": "numerical"
        },
        "PIGR": {
            "sdtype": "numerical"
        },
        "PON3": {
            "sdtype": "numerical"
        },
        "SERPINA3": {
            "sdtype": "numerical"
        },
        "VWF": {
            "sdtype": "numerical"
        }
    },
    "METADATA_SPEC_VERSION": "SINGLE_TABLE_V1"
}
Running tvae simulations:   0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

INFO: [2025-11-03 11:59:41] sdv.metadata.single_table - Detected metadata:
INFO: [2025-11-03 11:59:41] sdv.metadata.single_table - {
    "columns": {
        "ANPEP": {
            "sdtype": "numerical"
        },
        "APOA4": {
            "sdtype": "numerical"
        },
        "APOC3": {
            "sdtype": "numerical"
        },
        "C9": {
            "sdtype": "numerical"
        },
        "CRP": {
            "sdtype": "numerical"
        },
        "HGFAC": {
            "sdtype": "numerical"
        },
        "IGFBP2": {
            "sdtype": "numerical"
        },
        "ITIH3": {
            "sdtype": "numerical"
        },
        "LRG1": {
            "sdtype": "numerical"
        },
        "ORM1": {
            "sdtype": "numerical"
        },
        "PFN1": {
            "sdtype": "numerical"
        },
        "PIGR": {
            "sdtype": "numerical"
        },
        "PON3": {
            "sdtype": "numerical"
        },
        "SERPINA3": {
            "sdtype": "numerical"
        },
        "VWF": {
            "sdtype": "numerical"
        }
    },
    "METADATA_SPEC_VERSION": "SINGLE_TABLE_V1"
}

  0%|          | 0/10 [00:00<?, ?it/s]

INFO: [2025-11-03 11:59:52] sdv.metadata.single_table - Detected metadata:
INFO: [2025-11-03 11:59:52] sdv.metadata.single_table - {
    "columns": {
        "ANPEP": {
            "sdtype": "numerical"
        },
        "APOA4": {
            "sdtype": "numerical"
        },
        "APOC3": {
            "sdtype": "numerical"
        },
        "C9": {
            "sdtype": "numerical"
        },
        "CRP": {
            "sdtype": "numerical"
        },
        "HGFAC": {
            "sdtype": "numerical"
        },
        "IGFBP2": {
            "sdtype": "numerical"
        },
        "ITIH3": {
            "sdtype": "numerical"
        },
        "LRG1": {
            "sdtype": "numerical"
        },
        "ORM1": {
            "sdtype": "numerical"
        },
        "PFN1": {
            "sdtype": "numerical"
        },
        "PIGR": {
            "sdtype": "numerical"
        },
        "PON3": {
            "sdtype": "numerical"
        },
        "SERPINA3": {
            "sdtype": "numerical"
        },
        "VWF": {
            "sdtype": "numerical"
        }
    },
    "METADATA_SPEC_VERSION": "SINGLE_TABLE_V1"
}

  0%|          | 0/10 [00:00<?, ?it/s]

Running tvae simulations:   0%|          | 0/10 [00:33<?, ?it/s]
Running tvae simulations:   0%|          | 0/10 [00:15<?, ?it/s]

## Per-protein

### Single simulation

In [57]:
pprotein_sim_pdac_healthy_single = simulate_using_per_protein(
    pdac_dia_input_healthy, num_simulations=1,
    samples_per_simulation=len(pdac_dia_input_healthy), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

pprotein_sim_pdac_disease_single = simulate_using_per_protein(
    pdac_dia_input_disease, num_simulations=1,
    samples_per_simulation=len(pdac_dia_input_disease), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

pprotein_sim_pdac_benign_single = simulate_using_per_protein(
    pdac_dia_input_benign, num_simulations=1,
    samples_per_simulation=len(pdac_dia_input_benign), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

### Multiple simulations

In [58]:
pprotein_sim_pdac_healthy_multi = simulate_using_per_protein(
    pdac_dia_input_healthy, num_simulations=10,
    samples_per_simulation=len(pdac_dia_input_healthy), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

pprotein_sim_pdac_disease_multi = simulate_using_per_protein(
    pdac_dia_input_disease, num_simulations=10,
    samples_per_simulation=len(pdac_dia_input_disease), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

pprotein_sim_pdac_benign_multi = simulate_using_per_protein(
    pdac_dia_input_benign, num_simulations=10,
    samples_per_simulation=len(pdac_dia_input_benign), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

Running per-protein simulations:   0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

# PDAC - MRM

## Load and prepare data

In [64]:
pdac_mrm_input = pd.read_csv('../data/pdac/pdacsrm/data/pdac15srmdata.csv')
pdac_mrm_input.head()

,ANPEP,APOA4,APOC3,C9,CRP,HGFAC,IGFBP2,ITIH3,LRG1,ORM1,PFN1,PIGR,PON3,SERPINA3,VWF,Sample type
0,0.3842,-1.1623,-0.4501,0.4772,1.8914,-0.4745,-0.0560,0.5519,0.6890,0.6709,0.5459,0.3704,-1.2919,0.8489,0.4194,PDAC
1,-1.5007,0.6593,0.5924,-0.9269,0.1011,0.2823,-0.3448,-0.5023,-1.2196,-0.5317,1.2731,-0.7123,0.2863,-0.5646,-0.0317,Healthy
2,-0.7681,-0.0420,0.6603,-0.7134,-2.7858,0.5933,1.5475,-0.1785,-0.4674,-0.4857,0.2654,-1.6900,0.0602,-0.7405,0.2269,Healthy
3,0.5785,-0.6527,-1.2444,0.2480,-1.7489,0.1563,-0.2493,-0.4469,0.5103,-0.1690,0.1411,1.3436,0.1186,0.4217,0.4907,PDAC
4,1.3892,0.5066,-0.6367,0.0430,0.5124,-0.4203,0.2501,0.2817,0.1905,-0.1328,0.2994,1.1345,-0.0677,0.1311,0.2724,PDAC

In [71]:
from sklearn.impute import KNNImputer
import pandas as pd

# Keep original column order
orig_cols = pdac_mrm_input.columns.tolist()

# Split numeric and non-numeric columns (keep non-numeric like 'Sample type' intact)
numeric_cols = [c for c in orig_cols if pd.api.types.is_numeric_dtype(pdac_mrm_input[c])]
non_numeric_cols = [c for c in orig_cols if c not in numeric_cols]

# Report missing values before imputation
print("Missing values before imputation (numeric cols):")
print(pdac_mrm_input[numeric_cols].isna().sum())

# KNN imputation
imputer = KNNImputer(n_neighbors=5, weights="uniform")
imputed_array = imputer.fit_transform(pdac_mrm_input[numeric_cols])

# Build imputed DataFrame and restore original column order
imputed_numeric = pd.DataFrame(imputed_array, columns=numeric_cols, index=pdac_mrm_input.index)
pdac_mrm_input = pd.concat([pdac_mrm_input[non_numeric_cols], imputed_numeric], axis=1)[orig_cols]

# Report missing values after imputation
print("\nMissing values after imputation (numeric cols):")
print(pdac_mrm_input[numeric_cols].isna().sum())

Missing values before imputation (numeric cols):
ANPEP        0
APOA4        0
APOC3        0
C9           0
CRP         17
HGFAC        0
IGFBP2       6
ITIH3        0
LRG1         0
ORM1         0
PFN1         3
PIGR         0
PON3         0
SERPINA3     0
VWF          0
dtype: int64

Missing values after imputation (numeric cols):
ANPEP       0
APOA4       0
APOC3       0
C9          0
CRP         0
HGFAC       0
IGFBP2      0
ITIH3       0
LRG1        0
ORM1        0
PFN1        0
PIGR        0
PON3        0
SERPINA3    0
VWF         0
dtype: int64

In [72]:
# Split into health and disease
pdac_mrm_input_healthy = pdac_mrm_input[pdac_mrm_input['Sample type'] == "Healthy"].drop(columns=['Sample type'])
pdac_mrm_input_disease = pdac_mrm_input[pdac_mrm_input['Sample type'] == "PDAC"].drop(columns=['Sample type'])

## Copula

### Single simulation

In [73]:
copula_sim_pdac_mrm_healthy_single = simulate_using_copula(
    pdac_mrm_input_healthy, num_simulations=1, 
    samples_per_simulation=len(pdac_mrm_input_healthy), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

copula_sim_pdac_mrm_disease_single = simulate_using_copula(
    pdac_mrm_input_disease, num_simulations=1, 
    samples_per_simulation=len(pdac_mrm_input_disease), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

INFO: [2025-11-03 12:57:54] copulas.multivariate.gaussian - Fitting GaussianMultivariate()
INFO: [2025-11-03 12:57:57] copulas.multivariate.gaussian - Fitting GaussianMultivariate()

### Multiple simulations

In [74]:
copula_sim_pdac_mrm_healthy_multi = simulate_using_copula(
    pdac_mrm_input_healthy, num_simulations=10, 
    samples_per_simulation=len(pdac_mrm_input_healthy), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

copula_sim_pdac_mrm_disease_multi = simulate_using_copula(
    pdac_mrm_input_disease, num_simulations=10, 
    samples_per_simulation=len(pdac_mrm_input_disease), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=100
)

Running copula simulations:   0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

## TVAE

### Single simulation

In [75]:
tvae_sim_pdac_mrm_healthy_single = simulate_using_tvae(
    pdac_mrm_input_healthy, None, num_simulations=1,
    samples_per_simulation=len(pdac_mrm_input_healthy), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

tvae_sim_pdac_mrm_disease_single = simulate_using_tvae(
    pdac_mrm_input_disease, None, num_simulations=1,
    samples_per_simulation=len(pdac_mrm_input_disease),
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

INFO: [2025-11-03 12:59:58] sdv.metadata.single_table - Detected metadata:
INFO: [2025-11-03 12:59:58] sdv.metadata.single_table - {
    "columns": {
        "ANPEP": {
            "sdtype": "numerical"
        },
        "APOA4": {
            "sdtype": "numerical"
        },
        "APOC3": {
            "sdtype": "numerical"
        },
        "C9": {
            "sdtype": "numerical"
        },
        "CRP": {
            "sdtype": "numerical"
        },
        "HGFAC": {
            "sdtype": "numerical"
        },
        "IGFBP2": {
            "sdtype": "numerical"
        },
        "ITIH3": {
            "sdtype": "numerical"
        },
        "LRG1": {
            "sdtype": "numerical"
        },
        "ORM1": {
            "sdtype": "numerical"
        },
        "PFN1": {
            "sdtype": "numerical"
        },
        "PIGR": {
            "sdtype": "numerical"
        },
        "PON3": {
            "sdtype": "numerical"
        },
        "SERPINA3": {
            "sdtype": "numerical"
        },
        "VWF": {
            "sdtype": "numerical"
        }
    },
    "METADATA_SPEC_VERSION": "SINGLE_TABLE_V1"
}
INFO: [2025-11-03 12:59:58] SingleTableSynthesizer - {'EVENT': 'Instance', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 12, 59, 58, 387036), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_31cf3be0ec634173afba4aaf58791225'}
INFO: [2025-11-03 12:59:58] SingleTableSynthesizer - {'EVENT': 'Fit', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 12, 59, 58, 388161), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_31cf3be0ec634173afba4aaf58791225', 'TOTAL NUMBER OF TABLES': 1, 'TOTAL NUMBER OF ROWS': 39, 'TOTAL NUMBER OF COLUMNS': 15}
INFO: [2025-11-03 12:59:58] sdv.data_processing.data_processor - Fitting table  metadata
INFO: [2025-11-03 12:59:58] sdv.data_processing.data_processor - Fitting formatters for table
INFO: [2025-11-03 12:59:58] rdt.transformers.utils - No rounding scheme detected for column 'CRP'. Data will not be rounded.
INFO: [2025-11-03 12:59:58] rdt.transformers.utils - No rounding scheme detected for column 'IGFBP2'. Data will not be rounded.
INFO: [2025-11-03 12:59:58] sdv.data_processing.data_processor - Setting the configuration for the ``HyperTransformer`` for table
INFO: [2025-11-03 12:59:58] sdv.data_processing.data_processor - Fitting HyperTransformer for table
INFO: [2025-11-03 12:59:58] rdt.transformers.utils - No rounding scheme detected for column 'CRP'. Data will not be rounded.
INFO: [2025-11-03 12:59:58] rdt.transformers.utils - No rounding scheme detected for column 'IGFBP2'. Data will not be rounded.
INFO: [2025-11-03 12:59:58] SingleTableSynthesizer - {'EVENT': 'Fit processed data', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 12, 59, 58, 702709), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_31cf3be0ec634173afba4aaf58791225', 'TOTAL NUMBER OF TABLES': 1, 'TOTAL NUMBER OF ROWS': 39, 'TOTAL NUMBER OF COLUMNS': 15}
INFO: [2025-11-03 12:59:58] rdt.transformers.null - Guidance: There are no missing values in column ANPEP. Extra column not created.
INFO: [2025-11-03 12:59:58] rdt.transformers.null - Guidance: There are no missing values in column APOA4. Extra column not created.
INFO: [2025-11-03 12:59:58] rdt.transformers.null - Guidance: There are no missing values in column APOC3. Extra column not created.
INFO: [2025-11-03 12:59:58] rdt.transformers.null - Guidance: There are no missing values in column C9. Extra column not created.
INFO: [2025-11-03 12:59:58] rdt.transformers.null - Guidance: There are no missing values in column CRP. Extra column not created.
INFO: [2025-11-03 12:59:58] rdt.transformers.null - Guidance: There are no missing values in column HGFAC. Extra column not created.
INFO: [2025-11-03 12:59:59] rdt.transformers.null - Guidance: There are no missing values in column IGFBP2. Extra column not created.
INFO: [2025-11-03 12:59:59] rdt.transformers.null - Guidance: There are no missing values in column ITIH3. Extra column not created.
INFO: [2025-11-03 12:59:59] rdt.transformers.null - Guidance: There are no missing values in column LRG1. Extra column not created.
INFO: [2025-11-03 12:59:59] rdt.transformers.null - Guidance: There are no missing values in column ORM1. Extra column not created.
INFO: [2025-11-03 12:59:59] rdt.transformers.null - Guidance: There are no missing values in column PFN1. Extra column not created.
INFO: [2025-11-03 12:59:59] rdt.transformers.null - Guidance: There are no missing values in column PIGR. Extra column not created.
INFO: [2025-11-03 12:59:59] rdt.transformers.null - Guidance: There are no missing values in column PON3. Extra column not created.
INFO: [2025-11-03 12:59:59] rdt.transformers.null - Guidance: There are no missing values in column SERPINA3. Extra column not created.
Running copula simulations:   0%|          | 0/10 [00:53<?, ?it/s]
INFO: [2025-11-03 12:59:59] rdt.transformers.null - Guidance: There are no missing values in column VWF. Extra column not created.
INFO: [2025-11-03 13:00:05] SingleTableSynthesizer - {'EVENT': 'Sample', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 13, 0, 4, 909327), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_31cf3be0ec634173afba4aaf58791225', 'TOTAL NUMBER OF TABLES': 1, 'TOTAL NUMBER OF ROWS': 39, 'TOTAL NUMBER OF COLUMNS': 15}
INFO: [2025-11-03 13:00:05] sdv.metadata.single_table - Detected metadata:
INFO: [2025-11-03 13:00:05] sdv.metadata.single_table - {
    "columns": {
        "ANPEP": {
            "sdtype": "numerical"
        },
        "APOA4": {
            "sdtype": "numerical"
        },
        "APOC3": {
            "sdtype": "numerical"
        },
        "C9": {
            "sdtype": "numerical"
        },
        "CRP": {
            "sdtype": "numerical"
        },
        "HGFAC": {
            "sdtype": "numerical"
        },
        "IGFBP2": {
            "sdtype": "numerical"
        },
        "ITIH3": {
            "sdtype": "numerical"
        },
        "LRG1": {
            "sdtype": "numerical"
        },
        "ORM1": {
            "sdtype": "numerical"
        },
        "PFN1": {
            "sdtype": "numerical"
        },
        "PIGR": {
            "sdtype": "numerical"
        },
        "PON3": {
            "sdtype": "numerical"
        },
        "SERPINA3": {
            "sdtype": "numerical"
        },
        "VWF": {
            "sdtype": "numerical"
        }
    },
    "METADATA_SPEC_VERSION": "SINGLE_TABLE_V1"
}
INFO: [2025-11-03 13:00:05] SingleTableSynthesizer - {'EVENT': 'Instance', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 13, 0, 5, 24207), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_61f1ca76f75f48189343a710cfbd2d54'}
INFO: [2025-11-03 13:00:05] SingleTableSynthesizer - {'EVENT': 'Fit', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 13, 0, 5, 24753), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_61f1ca76f75f48189343a710cfbd2d54', 'TOTAL NUMBER OF TABLES': 1, 'TOTAL NUMBER OF ROWS': 40, 'TOTAL NUMBER OF COLUMNS': 15}
INFO: [2025-11-03 13:00:05] sdv.data_processing.data_processor - Fitting table  metadata
INFO: [2025-11-03 13:00:05] sdv.data_processing.data_processor - Fitting formatters for table
INFO: [2025-11-03 13:00:05] rdt.transformers.utils - No rounding scheme detected for column 'CRP'. Data will not be rounded.
INFO: [2025-11-03 13:00:05] rdt.transformers.utils - No rounding scheme detected for column 'PFN1'. Data will not be rounded.
INFO: [2025-11-03 13:00:05] sdv.data_processing.data_processor - Setting the configuration for the ``HyperTransformer`` for table
INFO: [2025-11-03 13:00:05] sdv.data_processing.data_processor - Fitting HyperTransformer for table
INFO: [2025-11-03 13:00:05] rdt.transformers.utils - No rounding scheme detected for column 'CRP'. Data will not be rounded.
INFO: [2025-11-03 13:00:05] rdt.transformers.utils - No rounding scheme detected for column 'PFN1'. Data will not be rounded.
INFO: [2025-11-03 13:00:05] SingleTableSynthesizer - {'EVENT': 'Fit processed data', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 13, 0, 5, 124906), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_61f1ca76f75f48189343a710cfbd2d54', 'TOTAL NUMBER OF TABLES': 1, 'TOTAL NUMBER OF ROWS': 40, 'TOTAL NUMBER OF COLUMNS': 15}
INFO: [2025-11-03 13:00:05] rdt.transformers.null - Guidance: There are no missing values in column ANPEP. Extra column not created.
INFO: [2025-11-03 13:00:05] rdt.transformers.null - Guidance: There are no missing values in column APOA4. Extra column not created.
INFO: [2025-11-03 13:00:05] rdt.transformers.null - Guidance: There are no missing values in column APOC3. Extra column not created.
INFO: [2025-11-03 13:00:05] rdt.transformers.null - Guidance: There are no missing values in column C9. Extra column not created.
INFO: [2025-11-03 13:00:05] rdt.transformers.null - Guidance: There are no missing values in column CRP. Extra column not created.
INFO: [2025-11-03 13:00:05] rdt.transformers.null - Guidance: There are no missing values in column HGFAC. Extra column not created.
INFO: [2025-11-03 13:00:05] rdt.transformers.null - Guidance: There are no missing values in column IGFBP2. Extra column not created.
INFO: [2025-11-03 13:00:05] rdt.transformers.null - Guidance: There are no missing values in column ITIH3. Extra column not created.
INFO: [2025-11-03 13:00:05] rdt.transformers.null - Guidance: There are no missing values in column LRG1. Extra column not created.
INFO: [2025-11-03 13:00:05] rdt.transformers.null - Guidance: There are no missing values in column ORM1. Extra column not created.
INFO: [2025-11-03 13:00:05] rdt.transformers.null - Guidance: There are no missing values in column PFN1. Extra column not created.
INFO: [2025-11-03 13:00:05] rdt.transformers.null - Guidance: There are no missing values in column PIGR. Extra column not created.
INFO: [2025-11-03 13:00:05] rdt.transformers.null - Guidance: There are no missing values in column PON3. Extra column not created.
INFO: [2025-11-03 13:00:05] rdt.transformers.null - Guidance: There are no missing values in column SERPINA3. Extra column not created.
INFO: [2025-11-03 13:00:05] rdt.transformers.null - Guidance: There are no missing values in column VWF. Extra column not created.
INFO: [2025-11-03 13:00:12] SingleTableSynthesizer - {'EVENT': 'Sample', 'TIMESTAMP': datetime.datetime(2025, 11, 3, 13, 0, 12, 214193), 'SYNTHESIZER CLASS NAME': 'TVAESynthesizer', 'SYNTHESIZER ID': 'TVAESynthesizer_1.28.0_61f1ca76f75f48189343a710cfbd2d54', 'TOTAL NUMBER OF TABLES': 1, 'TOTAL NUMBER OF ROWS': 40, 'TOTAL NUMBER OF COLUMNS': 15}

### Multiple simulations

In [76]:
tvae_sim_pdac_mrm_healthy_multi = simulate_using_tvae(
    pdac_mrm_input_healthy, None, num_simulations=10,
    samples_per_simulation=len(pdac_mrm_input_healthy), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

tvae_sim_pdac_mrm_disease_multi = simulate_using_tvae(
    pdac_mrm_input_disease, None, num_simulations=10,
    samples_per_simulation=len(pdac_mrm_input_disease), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

INFO: [2025-11-03 13:00:12] sdv.metadata.single_table - Detected metadata:
INFO: [2025-11-03 13:00:12] sdv.metadata.single_table - {
    "columns": {
        "ANPEP": {
            "sdtype": "numerical"
        },
        "APOA4": {
            "sdtype": "numerical"
        },
        "APOC3": {
            "sdtype": "numerical"
        },
        "C9": {
            "sdtype": "numerical"
        },
        "CRP": {
            "sdtype": "numerical"
        },
        "HGFAC": {
            "sdtype": "numerical"
        },
        "IGFBP2": {
            "sdtype": "numerical"
        },
        "ITIH3": {
            "sdtype": "numerical"
        },
        "LRG1": {
            "sdtype": "numerical"
        },
        "ORM1": {
            "sdtype": "numerical"
        },
        "PFN1": {
            "sdtype": "numerical"
        },
        "PIGR": {
            "sdtype": "numerical"
        },
        "PON3": {
            "sdtype": "numerical"
        },
        "SERPINA3": {
            "sdtype": "numerical"
        },
        "VWF": {
            "sdtype": "numerical"
        }
    },
    "METADATA_SPEC_VERSION": "SINGLE_TABLE_V1"
}
Running tvae simulations:   0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

INFO: [2025-11-03 13:00:28] sdv.metadata.single_table - Detected metadata:
INFO: [2025-11-03 13:00:28] sdv.metadata.single_table - {
    "columns": {
        "ANPEP": {
            "sdtype": "numerical"
        },
        "APOA4": {
            "sdtype": "numerical"
        },
        "APOC3": {
            "sdtype": "numerical"
        },
        "C9": {
            "sdtype": "numerical"
        },
        "CRP": {
            "sdtype": "numerical"
        },
        "HGFAC": {
            "sdtype": "numerical"
        },
        "IGFBP2": {
            "sdtype": "numerical"
        },
        "ITIH3": {
            "sdtype": "numerical"
        },
        "LRG1": {
            "sdtype": "numerical"
        },
        "ORM1": {
            "sdtype": "numerical"
        },
        "PFN1": {
            "sdtype": "numerical"
        },
        "PIGR": {
            "sdtype": "numerical"
        },
        "PON3": {
            "sdtype": "numerical"
        },
        "SERPINA3": {
            "sdtype": "numerical"
        },
        "VWF": {
            "sdtype": "numerical"
        }
    },
    "METADATA_SPEC_VERSION": "SINGLE_TABLE_V1"
}

  0%|          | 0/10 [00:00<?, ?it/s]

## Per-protein

### Single simulation

In [77]:
pprotein_sim_pdac_mrm_healthy_single = simulate_using_per_protein(
    pdac_mrm_input_healthy, num_simulations=1,
    samples_per_simulation=len(pdac_mrm_input_healthy), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

pprotein_sim_pdac_mrm_disease_single = simulate_using_per_protein(
    pdac_mrm_input_disease, num_simulations=1,
    samples_per_simulation=len(pdac_mrm_input_disease), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

Running tvae simulations:   0%|          | 0/10 [36:33<?, ?it/s]
Running tvae simulations:   0%|          | 0/10 [36:17<?, ?it/s]

### Multiple simulations

In [78]:
pprotein_sim_pdac_mrm_healthy_multi = simulate_using_per_protein(
    pdac_mrm_input_healthy, num_simulations=10,
    samples_per_simulation=len(pdac_mrm_input_healthy), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

pprotein_sim_pdac_mrm_disease_multi = simulate_using_per_protein(
    pdac_mrm_input_disease, num_simulations=10,
    samples_per_simulation=len(pdac_mrm_input_disease), # Set to size of input data to mirror variability
    output_dir=None, output_prefix='simulated',
    return_data=True, random_state=2
)

Running per-protein simulations:   0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

# Random Forest

## CRC

In [4]:
run_random_forest(crc_input, "Condition", len(crc_input), True, n_runs=10)

Running copula simulations:   0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

[0.8, 0.9, 0.775, 0.8, 0.975, 0.8, 0.9, 0.725, 0.925, 0.8]

In [25]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, StratifiedKFold, RandomizedSearchCV
from sklearn.metrics import accuracy_score

In [35]:
X = crc_input.drop(columns=['Condition'])
y = crc_input['Condition']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=2)

In [ ]:
param_grid = {
    "n_estimators": [200, 500, 1000],
    "max_depth": [None, 10, 20, 40],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4, 8],
    "max_features": ["sqrt", "log2", 0.5],
    "class_weight": [None, "balanced"]
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

search = RandomizedSearchCV(
    RandomForestClassifier(),
    param_distributions=param_grid,
    cv=cv,
    n_iter=30,
    scoring="accuracy",
    n_jobs=-1
)

search.fit(X_train, y_train)

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
                   estimator=RandomForestClassifier(), n_iter=30, n_jobs=-1,
                   param_distributions={'class_weight': [None, 'balanced'],
                                        'max_depth': [None, 10, 20, 40],
                                        'max_features': ['sqrt', 'log2', 0.5],
                                        'min_samples_leaf': [1, 2, 4, 8],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [200, 500, 1000]},
                   scoring='accuracy')

In [34]:
best_model = search.best_estimator_
y_pred = best_model.predict(X_test)
test_accuracy = accuracy_score(y_test, y_pred)
print("Test accuracy:", test_accuracy)

Test accuracy: 0.625

In [28]:
y_prob = best_model.predict_proba(X_test)[:, 1]

## MEL

## PDAC - DIA

## PDAC - MRM